// <auto-generated />
using System;
using FirmaAdvocacia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirmaAdvocacia.Migrations
{
    [DbContext(typeof(FirmaContext))]
    [Migration("20251123173459_infernodeprograma")]
    partial class infernodeprograma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirmaAdvocacia.Models.Advogado", b =>
                {
                    b.Property<int>("AdvogadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvogadoId"));

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OAB")
                        .HasColumnType("int");

                    b.HasKey("AdvogadoId");

                    b.ToTable("Advogados");
                });

            modelBuilder.Entity("FirmaAdvocacia.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FirmaAdvocacia.Models.ClienteProcesso", b =>
                {
                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int");

                    b.HasKey("ClienteId", "ProcessoId");

                    b.HasIndex("ProcessoId");

                    b.ToTable("ClientesProcessos");
                });

            modelBuilder.Entity("FirmaAdvocacia.Models.Processo", b =>
                {
                    b.Property<int>("ProcessoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessoId"));

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProcessoId");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("FirmaAdvocacia.Models.ClienteProcesso", b =>
                {
                    b.HasOne("FirmaAdvocacia.Models.Cliente", "ClienteOrigem")
                        .WithMany("ClientesProcessos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FirmaAdvocacia.Models.Processo", "ProcessoOrigem")
                        .WithMany("ClientesProcessos")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClienteOrigem");

                    b.Navigation("ProcessoOrigem");
                });

            modelBuilder.Entity("FirmaAdvocacia.Models.Cliente", b =>
                {
                    b.Navigation("ClientesProcessos");
                });

            modelBuilder.Entity("FirmaAdvocacia.Models.Processo", b =>
                {
                    b.Navigation("ClientesProcessos");
                });
#pragma warning restore 612, 618
        }
    }
}
